name: quickeydb
description: QuickeyDB is a simple ORM inspired from ActiveRecord, built on-top of Sqflite.

homepage: https://github.com/itskenzylimon/quickey

version: 1.2.1+9

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.0+2
  sqflite: ^2.3.0
  collection: ^1.17.2
  sqflite_common_ffi_web: ^0.4.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

  flutter_lints: ^2.0.3