name: quickeydb
description: QuickeyDB is a simple ORM inspired from ActiveRecord, built on-top of Sqflite.

homepage: https://github.com/itskenzylimon/quickey

version: 1.2.0+8

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.2.1+1
  sqflite: ^2.2.4+1
  collection: ^1.16.0
  sqflite_common_ffi_web: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

  flutter_lints: ^2.0.0